# Generated by Django 5.1.3 on 2024-11-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probidhans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probidhan',
            name='name',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='probidhan',
            name='starting_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
