# Generated by Django 5.1.3 on 2024-11-28 01:31

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.PositiveIntegerField(blank=True, max_length=10, null=True, validators=[students.models.validate_numeric]),
        ),
    ]
