# Generated by Django 5.1.3 on 2024-11-29 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0001_initial'),
        ('students', '0004_alter_student_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='student',
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_absents',
            field=models.ManyToManyField(blank=True, related_name='attendances_absent', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student_presents',
            field=models.ManyToManyField(related_name='attendances_present', to='students.student'),
        ),
    ]
