# Generated by Django 5.1.3 on 2024-11-29 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0002_remove_attendance_student_attendance_student_absents_and_more'),
        ('groups', '0001_initial'),
        ('students', '0004_alter_student_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_absents',
            field=models.ManyToManyField(blank=True, null=True, related_name='attendances_absent', to='students.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_presents',
            field=models.ManyToManyField(blank=True, null=True, related_name='attendances_present', to='students.student'),
        ),
    ]
