# Generated by Django 5.1.3 on 2024-11-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendances', '0003_attendance_group_alter_attendance_student_absents_and_more'),
        ('students', '0004_alter_student_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='student_absents',
            field=models.ManyToManyField(blank=True, related_name='attendances_absent', to='students.student'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student_presents',
            field=models.ManyToManyField(blank=True, related_name='attendances_present', to='students.student'),
        ),
    ]
