# Generated by Django 5.1.3 on 2024-11-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_alter_teacher_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='short_department',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='short_designation',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
