# Generated by Django 5.1.3 on 2025-03-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_teacher_short_department_teacher_short_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
