# Generated by Django 5.1.3 on 2024-11-22 19:16

import django.db.models.deletion
import subjects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        ('probidhans', '0001_initial'),
        ('semesters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, max_length=8, null=True, validators=[subjects.models.validate_numeric])),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('theory', models.CharField(blank=True, max_length=5, null=True, validators=[subjects.models.validate_numeric])),
                ('practical', models.CharField(blank=True, max_length=5, null=True, validators=[subjects.models.validate_numeric])),
                ('credit', models.CharField(blank=True, max_length=5, null=True, validators=[subjects.models.validate_numeric])),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='departments.department')),
                ('probidhan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='probidhans.probidhan')),
                ('semester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='semesters.semester')),
            ],
        ),
    ]
