# Generated by Django 5.1.3 on 2024-11-22 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
